# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: black
        name: black
        description: "Black: The uncompromising Python code formatter (with Jupyter Notebook support)"
        entry: poetry run black
        language: system
        types: [python]

      - id: isort-python
        name: isort
        entry: poetry run isort
        language: system
        types: [python]

      - id: commitizen
        name: commitizen check
        description: "Check whether the commit message follows committing rules"
        entry: cz check
        language: system
        files: ""
        stages: [commit-msg]
